services:
  backend:
    image: $GCR_REGION-docker.pkg.dev/$GCR_PROJECT_NAME/cloud-run-vpc-terraform-sample-repository/cloud-run-vpc-terraform-sample-backend:1
    build:
      context: .
      dockerfile: Dockerfile.backend

    ports:
      - 3000:3000
    
    networks:
      - cloud-run-vpc-terraform-sample-network
    
    environment:
      - BACKEND_PORT=3000

  frontend:
    image: $GCR_REGION-docker.pkg.dev/$GCR_PROJECT_NAME/cloud-run-vpc-terraform-sample-repository/cloud-run-vpc-terraform-sample-frontend:1
    build:
      context: .
      dockerfile: Dockerfile.frontend

    ports:
      - 4321:4321

    networks:
      - cloud-run-vpc-terraform-sample-network
    
    environment:
      - BACKEND_URL=http://backend:3000

networks:
  cloud-run-vpc-terraform-sample-network:
